version: "3"
services:
  postgres:
    container_name: pg-container
    image: postgres
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: encurtador
  api:
    container_name: api-container
    build: .
    image: encurtador
    restart: always
    command:
        bash -c "yarn typeorm:migrate
        && yarn start"
    ports:
      - "3333:3333"
    env_file:
      - .env
    links:
      - postgres
